version: '3'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always
  
  backend:
    build: ./backend/
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - static_value:/app/collected_static/
      - media_value:/app/media/
    ports:
      - "8000:8000"
  
  frontend:
    build: ./frontend/
    ports:
      - "80:80"
    volumes:
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data:
  static_value:
  media_value: 