version: '3'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always
  
  backend:
    build: ./backend/
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - static_value:/app/collected_static/
      - media_value:/app/media/
  
  frontend:
    build: ./frontend/
    volumes:
      - frontend_value:/app/result_build/
    depends_on:
      - backend
    command: cp -r /app/build/. /app/result_build/
  
  nginx:
    image: nginx:1.19
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - frontend_value:/usr/share/nginx/html/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
      - frontend
    restart: always

volumes:
  postgres_data:
  static_value:
  media_value:
  frontend_value: 