version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always

  backend:
    image: dsugakov/kittygram_backend:latest
    container_name: backend
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - SECRET_KEY=${SECRET_KEY}
      - DB_HOST=postgres
      - DB_PORT=5432
    volumes:
      - static:/app/collected_static
      - media:/app/media
    restart: always

  frontend:
    image: dsugakov/kittygram_frontend:latest
    container_name: frontend
    volumes:
      - frontend_static:/app/build/static
    restart: always

  gateway:
    image: dsugakov/kittygram_gateway:latest
    container_name: gateway
    ports:
      - "80:80"
    volumes:
      - static:/static
      - media:/media
      - frontend_static:/static/frontend
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always

volumes:
  pg_data:
  static:
  media:
  frontend_static: