name: Kittygram CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Print info
        run: echo "Kittygram workflow placeholder"

